# Generated by Django 5.1.1 on 2025-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
