# Generated by Django 5.1.1 on 2025-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentplayback',
            name='logged_playback',
            field=models.BooleanField(default=False),
        ),
    ]
