# Generated by Django 5.1.1 on 2025-04-04 15:51
 


 

from django.db import migrations, models
 


 


 

class Migration(migrations.Migration):
 


 

    dependencies = [
 

        ('api', '0004_remove_album_img_url'),
 

    ]
 


 

    operations = [
 

        migrations.AddField(
 

            model_name='artist',
 

            name='image',
 

            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
 

        ),
 

    ]