# Generated by Django 5.1.1 on 2025-04-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_managers_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='theme',
        ),
    ]
