# Generated by Django 5.2 on 2025-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
