# Generated by Django 5.1.1 on 2025-04-18 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_album_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_playback_song', to='api.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_playback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
