# Generated by Django 5.1.1 on 2025-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_currentplayback'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip-hop', 'Hip-Hop'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('country', 'Country'), ('electronic', 'Electronic'), ('reggae', 'Reggae'), ('rap', 'Rap'), ('r&b', 'R&B'), ('classical', 'Classical'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
