# Generated by Django 5.1.1 on 2025-04-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
