# Generated by Django 5.2 on 2025-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_playlist_songs_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='api.PlaylistSong', to='api.song'),
        ),
    ]
