# Generated by Django 5.1.1 on 2025-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_song_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
