# Generated by Django 5.2 on 2025-05-09 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_playlistsong_options_playlist_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
