# Generated by Django 5.1.1 on 2025-04-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_img_url'),
        ('api', '0011_remove_song_artist_album_album_type_alter_song_album'),
    ]

    operations = [
    ]
