# Generated by Django 5.2 on 2025-05-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_playbackhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='plays',
        ),
    ]
