# Generated by Django 5.1.1 on 2025-04-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250406_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='img_url',
        ),
    ]
