# Generated by Django 5.1.1 on 2025-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_album_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='theme',
            field=models.CharField(default='#777777', max_length=50),
        ),
    ]
