# Generated by Django 5.1.1 on 2025-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_album_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='api.artist'),
        ),
    ]
