# Generated by Django 5.1.1 on 2025-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_song_featured_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_indecent',
            field=models.BooleanField(default=False),
        ),
    ]
